name: Deploying Static Web App

on:
  push:
    branches:
      - main

env:
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Set this to your Azure Static Web Apps API token
  AZURE_STATIC_WEB_APPS_APP_LOCATION: '/'  # Set this to the location of your app files
  AZURE_STATIC_WEB_APPS_OUTPUT_LOCATION: 'build'  # Set this to the directory where the built app files are located
  NODE_VERSION: '16.x'  # Set this to the node version to use 

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          # Build and test the project, then deploy to Azure Static Web App.
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./

      - name: 'Deploy to Azure Static Web Apps'
        uses: Azure/static-web-apps-deploy@v1
        with: 
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # If the build output location is different from the root of the repository, specify it here
          # app_location: ${{ env.AZURE_STATIC_WEB_APPS_APP_LOCATION }}
          # output_location: ${{ env.AZURE_STATIC_WEB_APPS_OUTPUT_LOCATION }}
          deployment_action: 'upload'
        env:
          SKIP_DEPLOY_ON_MISSING_SECRETS: true
